POST http://localhost:3333/videos
Content-Type: application/json

{
  "tittle": "Video 1",
  "description": "Primeiro video do canal",
  "duration": 120
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/02903673-5caa-4de7-bc60-3d6b38f59161
Content-Type: application/json

{
  "tittle": "Video brabo",
  "description": "Primeiro video publicado",
  "duration": 120
}

###

DELETE http://localhost:3333/videos/02903673-5caa-4de7-bc60-3d6b38f59161